/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) car_kinematic_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

/* car_kinematic_cost_ext_cost_0_fun:(i0[6],i1[3],i2[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.;
  a1=-1.3845493629437283e-01;
  a2=arg[0]? arg[0][5] : 0;
  a1=(a1*a2);
  a3=5.9925004824816143e-02;
  a1=(a1+a3);
  a1=(a1*a2);
  a3=2.0059897207952213e-01;
  a1=(a1+a3);
  a1=(a1*a2);
  a3=2.3086484313215150e-01;
  a1=(a1+a3);
  a1=(a1*a2);
  a3=1.5878559642148511e+00;
  a1=(a1+a3);
  a1=(a1*a2);
  a4=1.3592101520430320e+00;
  a1=(a1+a4);
  a4=arg[0]? arg[0][0] : 0;
  a1=(a1-a4);
  a4=-6.9227468147186411e-01;
  a4=(a4*a2);
  a5=2.3970001929926457e-01;
  a4=(a4+a5);
  a4=(a4*a2);
  a5=6.0179691623856635e-01;
  a4=(a4+a5);
  a4=(a4*a2);
  a5=4.6172968626430300e-01;
  a4=(a4+a5);
  a4=(a4*a2);
  a4=(a4+a3);
  a3=casadi_sq(a4);
  a5=-3.9562898318218451e+00;
  a5=(a5*a2);
  a6=-3.7212344094208509e+00;
  a5=(a5+a6);
  a5=(a5*a2);
  a6=-8.3337619914141525e-01;
  a5=(a5+a6);
  a5=(a5*a2);
  a6=-7.7056638584115789e-01;
  a5=(a5+a6);
  a5=(a5*a2);
  a6=2.0690500327448431e+00;
  a5=(a5+a6);
  a7=casadi_sq(a5);
  a3=(a3+a7);
  a3=sqrt(a3);
  a4=(a4/a3);
  a7=(a1*a4);
  a8=-7.9125796636436907e-01;
  a8=(a8*a2);
  a9=-9.3030860235521273e-01;
  a8=(a8+a9);
  a8=(a8*a2);
  a9=-2.7779206638047177e-01;
  a8=(a8+a9);
  a8=(a8*a2);
  a9=-3.8528319292057894e-01;
  a8=(a8+a9);
  a8=(a8*a2);
  a8=(a8+a6);
  a8=(a8*a2);
  a6=2.3155917952757923e+00;
  a8=(a8+a6);
  a6=arg[0]? arg[0][1] : 0;
  a8=(a8-a6);
  a5=(a5/a3);
  a3=(a8*a5);
  a7=(a7+a3);
  a4=(a7*a4);
  a1=(a1-a4);
  a1=casadi_sq(a1);
  a5=(a7*a5);
  a8=(a8-a5);
  a8=casadi_sq(a8);
  a1=(a1+a8);
  a0=(a0*a1);
  a7=fabs(a7);
  a7=casadi_sq(a7);
  a0=(a0+a7);
  a7=5.0000000000000000e-01;
  a1=1.;
  a2=(a2-a1);
  a2=casadi_sq(a2);
  a7=(a7*a2);
  a0=(a0+a7);
  a7=arg[1]? arg[1][0] : 0;
  a7=casadi_sq(a7);
  a0=(a0+a7);
  a7=arg[1]? arg[1][1] : 0;
  a7=casadi_sq(a7);
  a0=(a0+a7);
  a7=arg[1]? arg[1][2] : 0;
  a7=casadi_sq(a7);
  a0=(a0+a7);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int car_kinematic_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int car_kinematic_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int car_kinematic_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_kinematic_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int car_kinematic_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_kinematic_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void car_kinematic_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void car_kinematic_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int car_kinematic_cost_ext_cost_0_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int car_kinematic_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real car_kinematic_cost_ext_cost_0_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_kinematic_cost_ext_cost_0_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_kinematic_cost_ext_cost_0_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_kinematic_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_kinematic_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int car_kinematic_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
